import { TokenEnum } from "./enums";

export const identifierKeywords: Record<string, TokenEnum> = {
  and: TokenEnum.AND,
  class: TokenEnum.CLASS,
  else: TokenEnum.ELSE,
  false: TokenEnum.FALSE,
  for: TokenEnum.FOR,
  fun: TokenEnum.FUN,
  if: TokenEnum.IF,
  nil: TokenEnum.NIL,
  or: TokenEnum.OR,
  print: TokenEnum.PRINT,
  return: TokenEnum.RETURN,
  super: TokenEnum.SUPER,
  this: TokenEnum.THIS,
  true: TokenEnum.TRUE,
  var: TokenEnum.VAR,
  while: TokenEnum.WHILE,
};

export const punctuationKeywords: Record<string, TokenEnum> = {
  ["("]: TokenEnum.LEFT_PAREN,
  [")"]: TokenEnum.RIGHT_PAREN,
  ["{"]: TokenEnum.LEFT_BRACE,
  ["}"]: TokenEnum.RIGHT_BRACE,
  [","]: TokenEnum.COMMA,
  ["."]: TokenEnum.DOT,
  ["-"]: TokenEnum.MINUS,
  ["+"]: TokenEnum.PLUS,
  [";"]: TokenEnum.SEMICOLON,
  ["*"]: TokenEnum.STAR,
  ["!"]: TokenEnum.BANG,
  ["!="]: TokenEnum.BANG_EQUAL,
  ["="]: TokenEnum.EQUAL,
  ["=="]: TokenEnum.EQUAL_EQUAL,
  ["<"]: TokenEnum.LESS,
  ["<="]: TokenEnum.LESS_EQUAL,
  [">"]: TokenEnum.GREATER,
  [">="]: TokenEnum.GREATER_EQUAL,
};
